"""add event_signal_type to cyber events

Revision ID: 01de1f14c818
Revises: fcf29c59c854
Create Date: 2026-04-16 22:03:53.588961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01de1f14c818'
down_revision = 'fcf29c59c854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_cve_links')
    op.drop_table('source_reputations')
    op.add_column('cyber_events', sa.Column('event_signal_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cyber_events', 'event_signal_type')
    op.create_table('source_reputations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reputation_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reputation_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('source_reputations_pkey')),
    sa.UniqueConstraint('source_name', name=op.f('source_reputations_source_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('event_cve_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cyber_event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cve_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cyber_event_id'], ['cyber_events.id'], name=op.f('event_cve_links_cyber_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('event_cve_links_pkey'))
    )
    # ### end Alembic commands ###
