"""create cyber_events table

Revision ID: 1d3fcc5748be
Revises: 28826af51207
Create Date: 2026-04-11 20:50:23.530021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3fcc5748be'
down_revision = '28826af51207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyber_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('event_status', sa.String(length=50), nullable=True),
    sa.Column('confidence_level', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('event_occurred_at', sa.DateTime(), nullable=True),
    sa.Column('victim_org_name', sa.String(length=255), nullable=True),
    sa.Column('victim_org_normalized', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('access_vector', sa.String(length=100), nullable=True),
    sa.Column('impact_type', sa.String(length=100), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=100), nullable=True),
    sa.Column('attribution_status', sa.String(length=100), nullable=True),
    sa.Column('vuln_status', sa.String(length=100), nullable=True),
    sa.Column('primary_cve_id', sa.String(length=50), nullable=True),
    sa.Column('zero_day_flag', sa.Boolean(), nullable=True),
    sa.Column('geography_type', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('high_credibility_source_count', sa.Integer(), nullable=True),
    sa.Column('event_cluster_key', sa.String(length=255), nullable=True),
    sa.Column('last_confidence_scored_at', sa.DateTime(), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(), nullable=True),
    sa.Column('summary_short', sa.Text(), nullable=True),
    sa.Column('summary_medium', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cyber_events')
    # ### end Alembic commands ###
