"""create article_extractions table

Revision ID: 28826af51207
Revises: d184f7c99b88
Create Date: 2026-04-11 20:39:01.525121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28826af51207'
down_revision = 'd184f7c99b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_article_id', sa.Integer(), nullable=False),
    sa.Column('victim_org_name', sa.String(length=255), nullable=True),
    sa.Column('victim_org_normalized', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('access_vector', sa.String(length=100), nullable=True),
    sa.Column('impact_type', sa.String(length=100), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=100), nullable=True),
    sa.Column('attribution_status', sa.String(length=100), nullable=True),
    sa.Column('vuln_status', sa.String(length=100), nullable=True),
    sa.Column('cve_ids', sa.JSON(), nullable=True),
    sa.Column('zero_day_flag', sa.Boolean(), nullable=True),
    sa.Column('short_event_summary', sa.Text(), nullable=True),
    sa.Column('extracted_signals', sa.JSON(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_extractions')
    # ### end Alembic commands ###
