"""Remove dead fields and EnrichmentAuditLog

Revision ID: 2f16ed21bf1d
Revises: 9d01d5797e34
Create Date: 2026-05-12 21:42:20.650342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f16ed21bf1d'
down_revision = '9d01d5797e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_audit_logs_event_id'), table_name='enrichment_audit_logs')
    op.drop_index(op.f('ix_enrichment_audit_logs_started_at'), table_name='enrichment_audit_logs')
    op.drop_table('enrichment_audit_logs')
    op.drop_column('cyber_events', 'event_occurred_at')
    op.drop_column('cyber_events', 'summary_medium')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cyber_events', sa.Column('summary_medium', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cyber_events', sa.Column('event_occurred_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('enrichment_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('article_called', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('web_called', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fields_before', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fields_after', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('article_returned', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('web_returned', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fields_filled', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('article_usage', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('web_usage', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('enrichment_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_enrichment_audit_logs_started_at'), 'enrichment_audit_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_enrichment_audit_logs_event_id'), 'enrichment_audit_logs', ['event_id'], unique=False)
    # ### end Alembic commands ###
