"""create event_cve_links table

Revision ID: 47fed34b6c2c
Revises: 7ace8da413a3
Create Date: 2026-04-11 20:59:49.398005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fed34b6c2c'
down_revision = '7ace8da413a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_cve_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cyber_event_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cyber_event_id'], ['cyber_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_cve_links')
    # ### end Alembic commands ###
