"""add actor_candidate_sightings table

Revision ID: 5c9454d998e3
Revises: 631d0f40fd43
Create Date: 2026-05-08 23:22:34.677599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9454d998e3'
down_revision = '631d0f40fd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_candidate_sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(length=160), nullable=False),
    sa.Column('raw_article_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_name', 'raw_article_id', name='uq_actor_candidate_sighting')
    )
    op.create_index(op.f('ix_actor_candidate_sightings_candidate_name'), 'actor_candidate_sightings', ['candidate_name'], unique=False)
    op.create_index(op.f('ix_actor_candidate_sightings_raw_article_id'), 'actor_candidate_sightings', ['raw_article_id'], unique=False)
    op.create_index(op.f('ix_actor_candidate_sightings_seen_at'), 'actor_candidate_sightings', ['seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actor_candidate_sightings_seen_at'), table_name='actor_candidate_sightings')
    op.drop_index(op.f('ix_actor_candidate_sightings_raw_article_id'), table_name='actor_candidate_sightings')
    op.drop_index(op.f('ix_actor_candidate_sightings_candidate_name'), table_name='actor_candidate_sightings')
    op.drop_table('actor_candidate_sightings')
    # ### end Alembic commands ###
