"""add enrichment_audit_logs table

Revision ID: 631d0f40fd43
Revises: 67dc176b4c08
Create Date: 2026-05-08 13:40:54.653041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631d0f40fd43'
down_revision = '67dc176b4c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('article_called', sa.Boolean(), nullable=True),
    sa.Column('web_called', sa.Boolean(), nullable=True),
    sa.Column('fields_before', sa.JSON(), nullable=True),
    sa.Column('fields_after', sa.JSON(), nullable=True),
    sa.Column('article_returned', sa.JSON(), nullable=True),
    sa.Column('web_returned', sa.JSON(), nullable=True),
    sa.Column('fields_filled', sa.JSON(), nullable=True),
    sa.Column('article_usage', sa.JSON(), nullable=True),
    sa.Column('web_usage', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_audit_logs_event_id'), 'enrichment_audit_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_enrichment_audit_logs_started_at'), 'enrichment_audit_logs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_audit_logs_started_at'), table_name='enrichment_audit_logs')
    op.drop_index(op.f('ix_enrichment_audit_logs_event_id'), table_name='enrichment_audit_logs')
    op.drop_table('enrichment_audit_logs')
    # ### end Alembic commands ###
