"""add ai_event_error to cyber_events

Revision ID: 67dc176b4c08
Revises: 848996ebd17d
Create Date: 2026-05-07 18:43:51.084289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67dc176b4c08'
down_revision = '848996ebd17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cyber_events', sa.Column('ai_event_error', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cyber_events', 'ai_event_error')
    # ### end Alembic commands ###
