"""drop actor_candidate_sightings table

Revision ID: 7758587c45dc
Revises: aa0fb51385f9
Create Date: 2026-05-13 14:19:31.174090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7758587c45dc'
down_revision = 'aa0fb51385f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actor_candidate_sightings_candidate_name'), table_name='actor_candidate_sightings')
    op.drop_index(op.f('ix_actor_candidate_sightings_raw_article_id'), table_name='actor_candidate_sightings')
    op.drop_index(op.f('ix_actor_candidate_sightings_seen_at'), table_name='actor_candidate_sightings')
    op.drop_table('actor_candidate_sightings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_candidate_sightings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_name', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('raw_article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('context_snippet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], name=op.f('actor_candidate_sightings_raw_article_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('actor_candidate_sightings_pkey')),
    sa.UniqueConstraint('candidate_name', 'raw_article_id', name=op.f('uq_actor_candidate_sighting'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_actor_candidate_sightings_seen_at'), 'actor_candidate_sightings', ['seen_at'], unique=False)
    op.create_index(op.f('ix_actor_candidate_sightings_raw_article_id'), 'actor_candidate_sightings', ['raw_article_id'], unique=False)
    op.create_index(op.f('ix_actor_candidate_sightings_candidate_name'), 'actor_candidate_sightings', ['candidate_name'], unique=False)
    # ### end Alembic commands ###
