"""create event_source_links table

Revision ID: 7ace8da413a3
Revises: 1d3fcc5748be
Create Date: 2026-04-11 20:56:33.041814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ace8da413a3'
down_revision = '1d3fcc5748be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_source_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cyber_event_id', sa.Integer(), nullable=False),
    sa.Column('raw_article_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('is_primary_source', sa.Boolean(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cyber_event_id'], ['cyber_events.id'], ),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_source_links')
    # ### end Alembic commands ###
