"""Add automation run tracking

Revision ID: 848996ebd17d
Revises: 01de1f14c818
Create Date: 2026-05-03 11:29:24.504073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848996ebd17d'
down_revision = '01de1f14c818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_runs')
    # ### end Alembic commands ###
