"""add content_enriched to raw_article

Revision ID: 9d01d5797e34
Revises: 5c9454d998e3
Create Date: 2026-05-11 22:19:19.083994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d01d5797e34'
down_revision = '5c9454d998e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_articles', sa.Column('content_enriched', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_articles', 'content_enriched')
    # ### end Alembic commands ###
