"""Remove ai_event_error vestigial field

Revision ID: aa0fb51385f9
Revises: 2f16ed21bf1d
Create Date: 2026-05-12 21:43:36.725034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0fb51385f9'
down_revision = '2f16ed21bf1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cyber_events', 'ai_event_error')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cyber_events', sa.Column('ai_event_error', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
