"""create source_reputations table

Revision ID: b090f192c94b
Revises: 47fed34b6c2c
Create Date: 2026-04-11 21:03:45.535642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b090f192c94b'
down_revision = '47fed34b6c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_reputations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('reputation_tier', sa.String(length=50), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('source_category', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_reputations')
    # ### end Alembic commands ###
